esphome:
  name: esp-tylo
  platform: esp32
  board: lolin_s2_mini
  includes:
    - esp_tylo.h

# WiFi configuration    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable logging
logger:

# Enable web server for monitoring
web_server:
  port: 80

# Enable OTA updates
ota:
  - platform: esphome
    password: "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Define UART component for RS485 communication
uart:
  id: uart_bus
  tx_pin: GPIO36
  rx_pin: GPIO35
  baud_rate: 19200
  parity: EVEN
  data_bits: 8
  stop_bits: 1

# Define GPIO pin for MAX485 DE/RE control
switch:
  - platform: gpio
    id: max485_de_re
    pin: GPIO33
    restore_mode: ALWAYS_OFF

# Template sensor to hold temperature data
sensor:
  - platform: template
    name: "Sauna Temperature Sensor"
    id: sauna_temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    update_interval: never

# Custom component
custom_component:
  - lambda: |-
      auto custom_sensor = new CustomSerialSensor(id(uart_bus), id(max485_de_re), id(sauna_temperature));
      App.register_component(custom_sensor);
      return {custom_sensor};

# Text sensor for displaying hex data
text_sensor:
  - platform: template
    name: "Hex Data"
    id: hex_data
    update_interval: never
    